# Numerical parity for the native Toto 2.0 4M port.
#
# Replays committed golden fixtures generated by the pinned official
# implementation (see .agents/generate-toto-reference.py). Loading the
# checkpoint needs the Hub cache, so the whole file is opt-in; the structural
# invariants that hold for any weights live in test-toto-synthetic.R and run
# everywhere.

toto_fixture_dir <- function() test_path("fixtures", "toto")

skip_unless_toto_checkpoint <- function() {
  skip_unless_checkpoint("toto2")
  skip_if_no_torch()
  skip_if_not_installed("jsonlite")
  skip_if_not(
    dir.exists(toto_fixture_dir()) &&
      length(list.files(toto_fixture_dir(), pattern = "\\.json$")) > 0,
    "No Toto golden fixtures; generate them per fixtures/README.md."
  )
}

read_toto_fixture <- function(path) {
  fixture <- jsonlite::fromJSON(path, simplifyVector = FALSE)
  fixture$contexts <- lapply(fixture$context_files, function(file) {
    connection <- file(file.path(dirname(path), file), open = "rb")
    on.exit(close(connection), add = TRUE)
    readBin(connection, "numeric", n = file.size(file.path(dirname(path), file)) %/% 4L,
            size = 4L, endian = "little")
  })
  fixture
}

toto_checkpoint_model <- function(revision) {
  paths <- vapply(
    c("config.json", "model.safetensors"),
    function(file) hfhub::hub_download("Datadog/Toto-2.0-4m", file, revision = revision),
    character(1)
  )
  config <- jsonlite::fromJSON(paths[["config.json"]])
  config$model_id <- "Datadog/Toto-2.0-4m"
  config$revision <- revision
  config$device <- "cpu"
  toto_constructor(
    config,
    safetensors::safe_load_file(paths[["model.safetensors"]], framework = "torch")
  )
}

test_that("native Toto matches the reference implementation on golden fixtures", {
  skip_unless_toto_checkpoint()

  fixtures <- sort(list.files(toto_fixture_dir(), pattern = "\\.json$", full.names = TRUE))
  model <- NULL
  for (path in fixtures) {
    fixture <- read_toto_fixture(path)
    expect_identical(fixture$schema_version, 1L)
    expect_identical(fixture$revision, "8306a9801cf98c0f5ffe4b2dcc8f496e616d84d9")
    if (is.null(model)) model <- toto_checkpoint_model(fixture$revision)

    levels <- unlist(fixture$quantile_levels)
    horizon <- as.integer(fixture$horizon)
    actual <- model$predict_batch_fn(
      fixture$contexts,
      rep(horizon, length(fixture$contexts)),
      levels,
      device = "cpu"
    )
    for (series in seq_along(fixture$contexts)) {
      expected <- matrix(
        unlist(fixture$expected_quantiles[[series]]),
        nrow = horizon, byrow = TRUE
      )
      expect_identical(dim(actual[[series]]), dim(expected))
      expect_close_f32(
        actual[[series]], expected,
        atol = fixture$atol, rtol = fixture$rtol
      )
    }
  }
})

test_that("the batched path reproduces per-series reference forecasts", {
  skip_unless_toto_checkpoint()

  # The two series in this fixture differ in length, so upstream cannot batch
  # them and generated each alone. The port pads them into one batch and must
  # still land on the same numbers -- which is the invariant that caught the
  # unobserved-patch masking bug.
  fixture <- read_toto_fixture(file.path(toto_fixture_dir(), "batch_agreement.json"))
  expect_false(length(fixture$contexts[[1]]) == length(fixture$contexts[[2]]))

  model <- toto_checkpoint_model(fixture$revision)
  levels <- unlist(fixture$quantile_levels)
  horizon <- as.integer(fixture$horizon)

  batched <- model$predict_batch_fn(
    fixture$contexts, rep(horizon, 2L), levels, device = "cpu"
  )
  for (series in 1:2) {
    expected <- matrix(
      unlist(fixture$expected_quantiles[[series]]), nrow = horizon, byrow = TRUE
    )
    expect_close_f32(batched[[series]], expected,
                     atol = fixture$atol, rtol = fixture$rtol)
    alone <- model$predict_fn(fixture$contexts[[series]], horizon, levels)
    expect_close_f32(batched[[series]], alone, atol = fixture$atol, rtol = fixture$rtol)
  }
})

test_that("Toto passes contract conformance against the real checkpoint", {
  skip_unless_toto_checkpoint()

  model <- toto_checkpoint_model("8306a9801cf98c0f5ffe4b2dcc8f496e616d84d9")
  report <- zuk_check_architecture(
    function(config, weights) model,
    context = 100 + 0.5 * seq_len(600) + 10 * sin(seq_len(600) * 2 * pi / 24),
    h = 24L,
    quantile_levels = c(0.1, 0.5, 0.9),
    error = FALSE
  )
  expect_false(any(!is.na(report$ok) & !report$ok))
})
