# Numerical parity for the native Chronos-2 port.
#
# Replays committed golden fixtures generated by the pinned official
# implementation (see .agents/generate-chronos2-reference.py). Loading the
# checkpoint needs the Hub cache, so the whole file is opt-in.

chronos2_fixture_dir <- function() test_path("fixtures", "chronos2")

skip_unless_chronos2_checkpoint <- function() {
  skip_if_not(identical(Sys.getenv("ZUK_RUN_CHECKPOINT_TEST"), "true"))
  skip_if_no_torch()
  skip_if_not_installed("jsonlite")
  skip_if_not(
    dir.exists(chronos2_fixture_dir()) &&
      length(list.files(chronos2_fixture_dir(), pattern = "\\.json$")) > 0,
    "No Chronos-2 golden fixtures; generate them per fixtures/README.md."
  )
}

read_chronos2_fixture <- function(path) {
  fixture <- jsonlite::fromJSON(path, simplifyVector = FALSE)
  fixture$contexts <- lapply(fixture$context_files, function(file) {
    full <- file.path(dirname(path), file)
    readBin(full, "numeric", n = file.size(full) %/% 4L, size = 4L, endian = "little")
  })
  fixture
}

chronos2_checkpoint_model <- function(revision) {
  paths <- vapply(
    c("config.json", "model.safetensors"),
    function(file) hfhub::hub_download("amazon/chronos-2", file, revision = revision),
    character(1)
  )
  config <- jsonlite::fromJSON(paths[["config.json"]])
  config$model_id <- "amazon/chronos-2"
  config$revision <- revision
  config$device <- "cpu"
  chronos2_constructor(
    config,
    safetensors::safe_load_file(paths[["model.safetensors"]], framework = "torch")
  )
}

fixture_groups <- function(fixture) {
  list(
    id = unlist(fixture$group_ids),
    target = unlist(fixture$targets),
    future = lapply(fixture$future, function(values) {
      if (!length(values)) NULL else unlist(values)
    })
  )
}

test_that("native Chronos-2 matches the reference on golden fixtures", {
  skip_unless_chronos2_checkpoint()

  fixtures <- sort(list.files(chronos2_fixture_dir(), pattern = "\\.json$",
                              full.names = TRUE))
  model <- NULL
  for (path in fixtures) {
    fixture <- read_chronos2_fixture(path)
    expect_identical(fixture$schema_version, 1L)
    expect_identical(fixture$revision, "29ec3766d36d6f73f0696f85560a422f50e8498c")
    if (is.null(model)) model <- chronos2_checkpoint_model(fixture$revision)

    levels <- unlist(fixture$quantile_levels)
    horizon <- as.integer(fixture$horizon)
    actual <- model$predict_batch_fn(
      fixture$contexts, rep(horizon, length(fixture$contexts)), levels,
      device = "cpu", groups = fixture_groups(fixture)
    )

    # One matrix per target row, never per context row.
    expect_length(actual, sum(unlist(fixture$targets)))
    for (series in seq_along(actual)) {
      expected <- matrix(unlist(fixture$expected_quantiles[[series]]),
                         nrow = horizon, byrow = TRUE)
      expect_identical(dim(actual[[series]]), dim(expected))
      expect_close_f32(actual[[series]], expected,
                       atol = fixture$atol, rtol = fixture$rtol)
    }
  }
})

test_that("a known future covariate changes the forecast it informs", {
  skip_unless_chronos2_checkpoint()

  fixture <- read_chronos2_fixture(
    file.path(chronos2_fixture_dir(), "future_covariate.json")
  )
  model <- chronos2_checkpoint_model(fixture$revision)
  levels <- unlist(fixture$quantile_levels)
  horizon <- as.integer(fixture$horizon)
  median_column <- which(abs(levels - 0.5) < 1e-9)

  informed <- model$predict_batch_fn(
    fixture$contexts, rep(horizon, 2L), levels, device = "cpu",
    groups = fixture_groups(fixture)
  )[[1]]

  # Matching the reference is necessary but not sufficient: a covariate wired
  # to nothing would agree with a reference wired the same wrong way. Flipping
  # the known future must move the forecast it informs.
  flip <- function(values) {
    groups <- fixture_groups(fixture)
    groups$future[[2]] <- rep(values, horizon)
    model$predict_batch_fn(fixture$contexts, rep(horizon, 2L), levels,
                           device = "cpu", groups = groups)[[1]]
  }
  on_forecast <- flip(1)
  off_forecast <- flip(0)
  expect_gt(max(abs(on_forecast[, median_column] - off_forecast[, median_column])), 1)
  expect_gt(mean(on_forecast[, median_column]), mean(off_forecast[, median_column]))
  expect_false(isTRUE(all.equal(informed, on_forecast)))
})

test_that("series in different tasks do not inform one another", {
  skip_unless_chronos2_checkpoint()

  fixture <- read_chronos2_fixture(
    file.path(chronos2_fixture_dir(), "independent_batch.json")
  )
  model <- chronos2_checkpoint_model(fixture$revision)
  levels <- unlist(fixture$quantile_levels)
  horizon <- as.integer(fixture$horizon)

  together <- model$predict_batch_fn(
    fixture$contexts, rep(horizon, 2L), levels, device = "cpu",
    groups = fixture_groups(fixture)
  )
  alone <- lapply(fixture$contexts, function(context) {
    model$predict_batch_fn(list(context), horizon, levels, device = "cpu",
                           groups = list(id = "1", target = TRUE,
                                         future = list(NULL)))[[1]]
  })
  for (series in 1:2) {
    expect_close_f32(together[[series]], alone[[series]],
                     atol = fixture$atol, rtol = fixture$rtol)
  }
})

test_that("Chronos-2 passes contract conformance against the real checkpoint", {
  skip_unless_chronos2_checkpoint()

  model <- chronos2_checkpoint_model("29ec3766d36d6f73f0696f85560a422f50e8498c")
  report <- zuk_check_architecture(
    function(config, weights) model,
    context = 100 + 0.5 * seq_len(600) + 10 * sin(seq_len(600) * 2 * pi / 24),
    h = 24L, quantile_levels = c(0.1, 0.5, 0.9), error = FALSE
  )
  expect_false(any(!is.na(report$ok) & !report$ok))
})
